// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

contract TRECRegistry is ERC721, EIP712, Ownable {
    uint256 private _nextTokenId;

    // The metadata attached to the bot's NFT
    struct AgentProfile {
        string ensName;
        uint256 creditScore;
        uint256 totalBorrowed;
        uint256 totalRepaid;
        bool isVerified; // True when BitGo KYC passes
    }

    mapping(uint256 => AgentProfile) public agentProfiles;
    // Links a user's wallet to their specific Agent NFT ID
    mapping(address => uint256) public userToAgentId; 

    // EIP-712 Cryptography setup for the BitGo Validator
    bytes32 private constant KYC_TYPEHASH = keccak256("KYCApproval(address user,bool approved)");
    address public bitgoValidator; // The backend wallet that signs the KYC approvals

    event AgentRegistered(address indexed owner, uint256 indexed tokenId, string ensName);
    event KYCVerified(uint256 indexed tokenId);
    event ScoreUpdated(uint256 indexed tokenId, uint256 newScore);

    constructor(address _bitgoValidator) 
        ERC721("TREC Agent ID", "TREC") 
        EIP712("TRECProtocol", "1") 
        Ownable(msg.sender) 
    {
        bitgoValidator = _bitgoValidator;
    }

    // --- 1. MINT THE AGENT NFT ---
    function registerAgent(string memory _ensName) external {
        require(userToAgentId[msg.sender] == 0, "You already have an Agent NFT");
        
        _nextTokenId++;
        uint256 tokenId = _nextTokenId;
        
        _mint(msg.sender, tokenId);
        userToAgentId[msg.sender] = tokenId;
        
        agentProfiles[tokenId] = AgentProfile({
            ensName: _ensName,
            creditScore: 0,
            totalBorrowed: 0,
            totalRepaid: 0,
            isVerified: false
        });

        emit AgentRegistered(msg.sender, tokenId, _ensName);
    }

    // --- 2. THE EIP-712 DIGITAL NOTARY (KYC) ---
    // Sky submits the signature generated by your Next.js backend
    function submitKYCSignature(bool _approved, bytes memory _signature) external {
        uint256 tokenId = userToAgentId[msg.sender];
        require(tokenId != 0, "No Agent NFT found");

        // Recreate the message hash that the backend signed
        bytes32 structHash = keccak256(abi.encode(KYC_TYPEHASH, msg.sender, _approved));
        bytes32 hash = _hashTypedDataV4(structHash);
        
        // Recover the address that signed the message
        address signer = ECDSA.recover(hash, _signature);
        
        // Check if the signature actually came from our official backend
        require(signer == bitgoValidator, "Invalid BitGo Signature! Scammer detected.");
        
        agentProfiles[tokenId].isVerified = _approved;
        emit KYCVerified(tokenId);
    }

    // --- 3. MAKE IT SOULBOUND ---
    // This OpenZeppelin v5 hook blocks people from transferring or selling the NFT
    function _update(address to, uint256 tokenId, address auth) internal override returns (address) {
        address from = _ownerOf(tokenId);
        // Allow minting (from = 0) and burning (to = 0), but block user-to-user transfers
        require(from == address(0) || to == address(0), "TREC Identity is Soulbound and cannot be sold!");
        return super._update(to, tokenId, auth);
    }

    // --- 4. VAULT ACTIONS ---
    function updateCreditScore(uint256 _tokenId, uint256 _newScore) external onlyOwner {
        agentProfiles[_tokenId].creditScore = _newScore;
        emit ScoreUpdated(_tokenId, _newScore);
    }
}